Update patch set 1
Patch Set 1:

The build because of issue in the jevents library.
====================================
rtest2.o: In function `main':
/home/jenkins/opnfv/slave_root/workspace/barometer-verify-master/src/pmu-tools/pmu-tools/jevents/examples/rtest2.c:22: multiple definition of `main'
/tmp/cc7CXSFA.o:/home/jenkins/opnfv/slave_root/workspace/barometer-verify-master/src/pmu-tools/pmu-tools/jevents/examples/rtest3.c:26: first defined here
rtest2.o: In function `main':
/home/jenkins/opnfv/slave_root/workspace/barometer-verify-master/src/pmu-tools/pmu-tools/jevents/examples/rtest2.c:37: undefined reference to `sin'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'rtest3' failed
make[3]: *** [rtest3] Error 1

Patch-set: 1
Label: Verified=0